cache:
  key: 'cache'
  paths:
    - .m2/repository/

stages:
  - build
  - package
  - create-image
  - deploy

variables:
  MAVEN_CLI_OPTS: '-s .m2/settings.xml --batch-mode'
  MAVEN_OPTS: '-Dmaven.repo.local=.m2/repository'
  APP_VERSION: '2022.04.1'

before_script:
  #  Alttaki sat覺r覺 her defas覺nda yapmas覺na gerek yok
  - chmod +x mvnw

maven-compile:
  only:
    - pushes
    - master
  stage: build
  script:
    - echo $MAVEN_CLI_OPTS $MAVEN_OPTS
    - echo $MAVEN_CLI_OPTS
      - ./mvnw compile $MAVEN_CLI_OPTS $MAVEN_OPTS

maven-package:
  only:
    - pushes
    - master
  stage: package
  script:
    - ./mvnw verify -Pprod -DskipTests $MAVEN_CLI_OPTS $MAVEN_OPTS

create-image:
  only:
    - master
  stage: create-image
  before_script:
    - chmod +x mvnw
    - 'echo "APP Version: $APP_VERSION"'
    - docker login registry.hub.docker.com -u apinizercloud -p PrvSoft.1!
  script:
    - 'echo "Image_TAG Version: registry.hub.docker.com/apinizercloud/example-service:$APP_VERSION"'
    - ./mvnw package $MAVEN_CLI_OPTS $MAVEN_OPTS -Pprod jib:build -Djib.to.image=registry.hub.docker.com/apinizercloud/example-service:$APP_VERSION

k8s-deploy:
  only:
    - master
  stage: deploy
  dependencies:
#    - create-image
  before_script:
    - 'echo "Path:$CI_PROJECT_DIR"'
    - 'echo "APP Version: $APP_VERSION"'
  script:
    - 'echo "Image_TAG Version: registry.hub.docker.com/apinizercloud/example-service:$APP_VERSION"'
    - /home/gitlab-runner/kubectl config set-cluster k8s --server="https://173.249.54.199:6443" --insecure-skip-tls-verify=true
    - /home/gitlab-runner/kubectl config set-credentials admin --token="eyJhbGciOiJSUzI1NiIsImtpZCI6IkJVMVFaZVBoNWk2VWFnM1BPS2NUMDdtbElaY1p6Q19aMWk5Y3REQTRXa28ifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJkZXBsb3ltZW50LWNvbnRyb2xsZXItdG9rZW4tNWttczkiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoiZGVwbG95bWVudC1jb250cm9sbGVyIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiMWU2N2RkMjctNTZlNC00NTExLTg5MjgtNDAyOTFmOGE4N2NjIiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50Omt1YmUtc3lzdGVtOmRlcGxveW1lbnQtY29udHJvbGxlciJ9.iPgEbXJESyqMMrZPjVPyopgcYOSPjyCia2nrBUw0COyToXUJXfyPHPDHXYI_3Il-0FJ6gWzv1NukWtCuvwWTvhwbS7FWNFlGgxdn8bOah7O_JX4Vyz9hZ3lSMriKFjrjle0g72tjCn55PeRcvX4GTzW-6_PrIn23TxYNVvT9vapXYRy8FETBeKKsvC6MS1w1EpyorD3XHKcJA-dLMr4I0_Pe_JLj05SZ1eJV6Zkq4n_APjjgIbhiRhOBozmddshriZb9oo0kpyywNdanK1AfNnTmy40DYAoUlQ0Qekvn97dGbeO4kDKXTF_E8FL8Ky00U8ujGkc0y70ubmNGacvpzg"
    - /home/gitlab-runner/kubectl config set-context default --cluster=k8s --user=admin
    - /home/gitlab-runner/kubectl config use-context default
    - /home/gitlab-runner/kubectl set image deployment/example-service example-service=apinizercloud/example-service:$APP_VERSION -n example-service
    - /home/gitlab-runner/kubectl delete replicasets,pods --all --grace-period=0 --force -n example-service
